"""Publicación de snapshots en IPFS.

English:
    Snapshot publication to IPFS.
"""

import json
import os
from typing import Any, Dict

DEFAULT_IPFS_ADDR = "/dns/localhost/tcp/5001/http"


def upload_snapshot_to_ipfs(json_data: Dict[str, Any]) -> str:
    """Sube un snapshot en JSON a IPFS y devuelve el CID.

    Args:
        json_data (Dict[str, Any]): Snapshot en formato dict.

    Returns:
        str: CID generado por IPFS.

    English:
        Uploads a JSON snapshot to IPFS and returns the CID.

    Args:
        json_data (Dict[str, Any]): Snapshot dictionary.

    Returns:
        str: CID generated by IPFS.
    """
    if os.getenv("IPFS_ENABLED", "false").lower() not in {"1", "true", "yes"}:
        return ""
    ipfs_addr = os.getenv("IPFS_API_URL", DEFAULT_IPFS_ADDR)
    try:
        import ipfshttpclient
    except ModuleNotFoundError:
        return ""
    client = ipfshttpclient.connect(ipfs_addr)
    try:
        payload = json.dumps(json_data, ensure_ascii=False)
        return client.add_json(payload)
    finally:
        client.close()
